"""initial schema

Revision ID: 333875b6aca9
Revises: 
Create Date: 2026-08-24 09:53:18.270240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333875b6aca9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=150), nullable=False),
    sa.Column('property_type', sa.Enum('APARTMENT', 'VILLA', 'COMMERCIAL', 'OFFICE', 'WAREHOUSE', name='propertytype'), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'UNDER_MAINTENANCE', name='propertystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_is_deleted'), 'properties', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_properties_property_name'), 'properties', ['property_name'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'PROPERTY_MANAGER', 'FACILITY_MANAGER', 'MAINTENANCE_STAFF', 'SECURITY_STAFF', 'TENANT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('building_name', sa.String(length=150), nullable=False),
    sa.Column('number_of_floors', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_is_deleted'), 'buildings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_buildings_property_id'), 'buildings', ['property_id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=150), nullable=False),
    sa.Column('facility_type', sa.Enum('GYM', 'SWIMMING_POOL', 'CONFERENCE_ROOM', 'CLUB_HOUSE', 'SPORTS_AREA', name='facilitytype'), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_facility_type'), 'facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_index(op.f('ix_facilities_property_id'), 'facilities', ['property_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('identification_number', sa.String(length=60), nullable=False),
    sa.Column('emergency_contact', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_index(op.f('ix_tenants_full_name'), 'tenants', ['full_name'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_identification_number'), 'tenants', ['identification_number'], unique=True)
    op.create_index(op.f('ix_tenants_is_deleted'), 'tenants', ['is_deleted'], unique=False)
    op.create_table('facility_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_bookings_booking_date'), 'facility_bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_facility_bookings_facility_id'), 'facility_bookings', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_id'), 'facility_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_status'), 'facility_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_facility_bookings_tenant_id'), 'facility_bookings', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('parking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('parking_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=True),
    sa.Column('vehicle_type', sa.Enum('CAR', 'BIKE', 'SUV', 'OTHER', name='parkingvehicletype'), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'BLOCKED', name='parkingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_slots_id'), 'parking_slots', ['id'], unique=False)
    op.create_index(op.f('ix_parking_slots_parking_number'), 'parking_slots', ['parking_number'], unique=False)
    op.create_index(op.f('ix_parking_slots_property_id'), 'parking_slots', ['property_id'], unique=False)
    op.create_index(op.f('ix_parking_slots_status'), 'parking_slots', ['status'], unique=False)
    op.create_index(op.f('ix_parking_slots_tenant_id'), 'parking_slots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_parking_slots_vehicle_number'), 'parking_slots', ['vehicle_number'], unique=True)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=30), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.Enum('STUDIO', 'ONE_BHK', 'TWO_BHK', 'THREE_BHK', 'OFFICE', 'SHOP', 'WAREHOUSE_UNIT', name='unittype'), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('monthly_rent', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', name='unitstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'unit_number', name='uq_unit_number_per_building')
    )
    op.create_index(op.f('ix_units_building_id'), 'units', ['building_id'], unique=False)
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_is_deleted'), 'units', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_units_status'), 'units', ['status'], unique=False)
    op.create_index(op.f('ix_units_unit_number'), 'units', ['unit_number'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_rent', sa.Float(), nullable=False),
    sa.Column('security_deposit', sa.Float(), nullable=False),
    sa.Column('lease_status', sa.Enum('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED', name='leasestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_id'), 'leases', ['id'], unique=False)
    op.create_index(op.f('ix_leases_is_deleted'), 'leases', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leases_lease_status'), 'leases', ['lease_status'], unique=False)
    op.create_index(op.f('ix_leases_tenant_id'), 'leases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_leases_unit_id'), 'leases', ['unit_id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY', name='maintenancepriority'), nullable=False),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='maintenancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_assigned_staff_id'), 'maintenance_requests', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_id'), 'maintenance_requests', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_priority'), 'maintenance_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_status'), 'maintenance_requests', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_tenant_id'), 'maintenance_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_unit_id'), 'maintenance_requests', ['unit_id'], unique=False)
    op.create_table('utility_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('utility_type', sa.Enum('ELECTRICITY', 'WATER', 'GAS', 'INTERNET', name='utilitytype'), nullable=False),
    sa.Column('previous_reading', sa.Float(), nullable=False),
    sa.Column('current_reading', sa.Float(), nullable=False),
    sa.Column('units_consumed', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utility_readings_billing_month'), 'utility_readings', ['billing_month'], unique=False)
    op.create_index(op.f('ix_utility_readings_id'), 'utility_readings', ['id'], unique=False)
    op.create_index(op.f('ix_utility_readings_unit_id'), 'utility_readings', ['unit_id'], unique=False)
    op.create_index(op.f('ix_utility_readings_utility_type'), 'utility_readings', ['utility_type'], unique=False)
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visitor_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('visitor_status', sa.Enum('EXPECTED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', name='visitorstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_id'), 'visitors', ['id'], unique=False)
    op.create_index(op.f('ix_visitors_tenant_id'), 'visitors', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_visitors_unit_id'), 'visitors', ['unit_id'], unique=False)
    op.create_index(op.f('ix_visitors_visitor_status'), 'visitors', ['visitor_status'], unique=False)
    op.create_table('maintenance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_history_id'), 'maintenance_history', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_history_request_id'), 'maintenance_history', ['request_id'], unique=False)
    op.create_table('rent_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('rent_amount', sa.Float(), nullable=False),
    sa.Column('late_fee', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lease_id', 'billing_month', name='uq_invoice_per_lease_per_month')
    )
    op.create_index(op.f('ix_rent_invoices_billing_month'), 'rent_invoices', ['billing_month'], unique=False)
    op.create_index(op.f('ix_rent_invoices_id'), 'rent_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_rent_invoices_lease_id'), 'rent_invoices', ['lease_id'], unique=False)
    op.create_index(op.f('ix_rent_invoices_status'), 'rent_invoices', ['status'], unique=False)
    op.create_table('utility_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('utility_type', sa.Enum('ELECTRICITY', 'WATER', 'GAS', 'INTERNET', name='utilitytype'), nullable=False),
    sa.Column('billing_month', sa.String(length=7), nullable=False),
    sa.Column('units_consumed', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='utilityinvoicestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['utility_readings.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utility_invoices_billing_month'), 'utility_invoices', ['billing_month'], unique=False)
    op.create_index(op.f('ix_utility_invoices_id'), 'utility_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_utility_invoices_reading_id'), 'utility_invoices', ['reading_id'], unique=True)
    op.create_index(op.f('ix_utility_invoices_unit_id'), 'utility_invoices', ['unit_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['rent_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_utility_invoices_unit_id'), table_name='utility_invoices')
    op.drop_index(op.f('ix_utility_invoices_reading_id'), table_name='utility_invoices')
    op.drop_index(op.f('ix_utility_invoices_id'), table_name='utility_invoices')
    op.drop_index(op.f('ix_utility_invoices_billing_month'), table_name='utility_invoices')
    op.drop_table('utility_invoices')
    op.drop_index(op.f('ix_rent_invoices_status'), table_name='rent_invoices')
    op.drop_index(op.f('ix_rent_invoices_lease_id'), table_name='rent_invoices')
    op.drop_index(op.f('ix_rent_invoices_id'), table_name='rent_invoices')
    op.drop_index(op.f('ix_rent_invoices_billing_month'), table_name='rent_invoices')
    op.drop_table('rent_invoices')
    op.drop_index(op.f('ix_maintenance_history_request_id'), table_name='maintenance_history')
    op.drop_index(op.f('ix_maintenance_history_id'), table_name='maintenance_history')
    op.drop_table('maintenance_history')
    op.drop_index(op.f('ix_visitors_visitor_status'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_unit_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_tenant_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_utility_readings_utility_type'), table_name='utility_readings')
    op.drop_index(op.f('ix_utility_readings_unit_id'), table_name='utility_readings')
    op.drop_index(op.f('ix_utility_readings_id'), table_name='utility_readings')
    op.drop_index(op.f('ix_utility_readings_billing_month'), table_name='utility_readings')
    op.drop_table('utility_readings')
    op.drop_index(op.f('ix_maintenance_requests_unit_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_tenant_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_status'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_priority'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_assigned_staff_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_leases_unit_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_tenant_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_lease_status'), table_name='leases')
    op.drop_index(op.f('ix_leases_is_deleted'), table_name='leases')
    op.drop_index(op.f('ix_leases_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_units_unit_number'), table_name='units')
    op.drop_index(op.f('ix_units_status'), table_name='units')
    op.drop_index(op.f('ix_units_is_deleted'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_index(op.f('ix_units_building_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_parking_slots_vehicle_number'), table_name='parking_slots')
    op.drop_index(op.f('ix_parking_slots_tenant_id'), table_name='parking_slots')
    op.drop_index(op.f('ix_parking_slots_status'), table_name='parking_slots')
    op.drop_index(op.f('ix_parking_slots_property_id'), table_name='parking_slots')
    op.drop_index(op.f('ix_parking_slots_parking_number'), table_name='parking_slots')
    op.drop_index(op.f('ix_parking_slots_id'), table_name='parking_slots')
    op.drop_table('parking_slots')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_facility_bookings_tenant_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_status'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_facility_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_booking_date'), table_name='facility_bookings')
    op.drop_table('facility_bookings')
    op.drop_index(op.f('ix_tenants_is_deleted'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_identification_number'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_full_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_facilities_property_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_type'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_buildings_property_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_is_deleted'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_name'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_deleted'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
